import importlib.util
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "scripts" / "build_paper_tables.py"


def load_table_builder():
    spec = importlib.util.spec_from_file_location("build_paper_tables", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


class PaperTableGenerationTests(unittest.TestCase):
    def test_renders_frontier_and_failure_tables_from_committed_artifacts(self) -> None:
        table_builder = load_table_builder()

        rendered = table_builder.render_tables(REPO_ROOT)

        self.assertIn("% Generated by scripts/build_paper_tables.py; do not edit by hand.", rendered)
        self.assertIn(r"\newcommand{\LsdPaperArtifactCount}{9}", rendered)
        self.assertIn(r"\label{tab:f1024-profile-frontier}", rendered)
        self.assertIn(r"\label{tab:validation-selected-reliability-probe}", rendered)
        self.assertIn(r"\label{tab:low-budget-failure-probe}", rendered)
        self.assertIn(r"\label{tab:post-hoc-policy-envelope}", rendered)
        self.assertIn(r"\label{tab:validation-portfolio-selector}", rendered)
        self.assertIn("Post-hoc policy envelope", rendered)
        self.assertIn("Validation portfolio selector", rendered)
        self.assertIn("16x8 f1024", rendered)
        self.assertIn("8x8 f1024", rendered)
        self.assertIn("Raw text", rendered)
        self.assertIn("Agreement-gated", rendered)
        self.assertIn("Validation-ranked", rendered)
        self.assertIn("MDL rule expansion", rendered)
        self.assertIn("non-deployable", rendered)
        self.assertIn("No target", rendered)
        self.assertIn("0.153", rendered)
        self.assertIn("-0.126", rendered)
        self.assertIn("0.062", rendered)
        self.assertIn("-0.111", rendered)
        self.assertIn("-0.037", rendered)
        self.assertIn("0.086", rendered)
        self.assertIn("0.007", rendered)
        self.assertIn("0.109", rendered)
        self.assertIn("0.000627", rendered)

    def test_latex_escapes_artifact_labels_and_writes_output(self) -> None:
        table_builder = load_table_builder()

        self.assertEqual(
            table_builder.latex_escape("epochs=16_hidden=8_features=1024"),
            r"epochs=16\_hidden=8\_features=1024",
        )

        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "results_tables.tex"
            table_builder.write_tables(REPO_ROOT, output_path)
            written = output_path.read_text()

        self.assertIn(r"\begin{table}", written)
        self.assertIn(r"\bottomrule", written)

    def test_committed_generated_tables_match_artifacts_and_are_input_by_paper(self) -> None:
        table_builder = load_table_builder()

        generated_path = REPO_ROOT / "paper" / "generated" / "results_tables.tex"
        main_tex = (REPO_ROOT / "paper" / "main.tex").read_text()

        self.assertEqual(generated_path.read_text(), table_builder.render_tables(REPO_ROOT))
        self.assertIn(r"\input{generated/results_tables.tex}", main_tex)


if __name__ == "__main__":
    unittest.main()
