import importlib.util
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "scripts" / "build_paper_tables.py"


def load_table_builder():
    spec = importlib.util.spec_from_file_location("build_paper_tables", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


class PaperTableGenerationTests(unittest.TestCase):
    def test_renders_frontier_and_failure_tables_from_committed_artifacts(self) -> None:
        table_builder = load_table_builder()

        rendered = table_builder.render_tables(REPO_ROOT)

        self.assertIn("% Generated by scripts/build_paper_tables.py; do not edit by hand.", rendered)
        self.assertIn(r"\newcommand{\LsdPaperArtifactCount}{29}", rendered)
        self.assertIn(r"\label{tab:f1024-profile-frontier}", rendered)
        self.assertIn(r"\label{tab:validation-selected-reliability-probe}", rendered)
        self.assertIn(r"\label{tab:low-budget-failure-probe}", rendered)
        self.assertIn(r"\label{tab:post-hoc-policy-envelope}", rendered)
        self.assertIn(r"\label{tab:validation-portfolio-selector}", rendered)
        self.assertIn(r"\label{tab:selector-transfer-stress}", rendered)
        self.assertIn(r"\label{tab:generated-label-audit}", rendered)
        self.assertIn(r"\label{tab:generated-coverage-audit}", rendered)
        self.assertIn(r"\label{tab:validation-coverage-proxy}", rendered)
        self.assertIn(r"\label{tab:validation-coverage-prior}", rendered)
        self.assertIn(r"\label{tab:tempered-sample-aware}", rendered)
        self.assertIn(r"\label{tab:train-size-gated-baseline}", rendered)
        self.assertIn(r"\label{tab:compact-train-size-gated}", rendered)
        self.assertIn(r"\label{tab:diversity-interaction}", rendered)
        self.assertIn(r"\label{tab:density-capped-compact}", rendered)
        self.assertIn(r"\label{tab:support-ramped-compact}", rendered)
        self.assertIn(r"\label{tab:late-confidence-ramped-compact}", rendered)
        self.assertIn(r"\label{tab:density-window-compact}", rendered)
        self.assertIn(r"\label{tab:train-support-density-selector}", rendered)
        self.assertIn(r"\label{tab:support-probe-window-selector}", rendered)
        self.assertIn(r"\label{tab:validation-support-precision-selector}", rendered)
        self.assertIn(r"\label{tab:validation-support-precision-gate}", rendered)
        self.assertIn(r"\label{tab:support-selector-transfer}", rendered)
        self.assertIn("Fresh-seed selector transfer", rendered)
        self.assertIn("Generated-label audit", rendered)
        self.assertIn("Generated-coverage audit", rendered)
        self.assertIn("Validation coverage proxy", rendered)
        self.assertIn("Coverage-prior selector", rendered)
        self.assertIn("Tempered sample-aware", rendered)
        self.assertIn("Unseen-seed train-size gated baseline", rendered)
        self.assertIn("Compact train-size gated", rendered)
        self.assertIn("Diversity interaction", rendered)
        self.assertIn("Sample-aware diverse", rendered)
        self.assertIn("Compact diverse", rendered)
        self.assertIn("Density-capped compact", rendered)
        self.assertIn("Support-ramped compact", rendered)
        self.assertIn("Late-confidence compact", rendered)
        self.assertIn("Density-window compact", rendered)
        self.assertIn("Train support-density selector", rendered)
        self.assertIn("Support-probe window selector", rendered)
        self.assertIn("Validation support-precision selector", rendered)
        self.assertIn("No-window validation support-precision gate", rendered)
        self.assertIn("Support-selector transfer stress", rendered)
        self.assertIn("Post-hoc policy envelope", rendered)
        self.assertIn("Validation portfolio selector", rendered)
        self.assertIn("Linear proxy selector", rendered)
        self.assertIn("Abstaining proxy selector", rendered)
        self.assertIn("16x8 f1024", rendered)
        self.assertIn("8x8 f1024", rendered)
        self.assertIn("Raw text", rendered)
        self.assertIn("Train-size gated sample-aware", rendered)
        self.assertIn("Agreement-gated", rendered)
        self.assertIn("Validation-ranked", rendered)
        self.assertIn("MDL rule expansion", rendered)
        self.assertIn("non-deployable", rendered)
        self.assertIn("No target", rendered)
        self.assertIn("0.153", rendered)
        self.assertIn("-0.126", rendered)
        self.assertIn("0.062", rendered)
        self.assertIn("-0.111", rendered)
        self.assertIn("-0.037", rendered)
        self.assertIn("0.086", rendered)
        self.assertIn("0.007", rendered)
        self.assertIn("0.109", rendered)
        self.assertIn("0.000627", rendered)
        self.assertIn("0.002091", rendered)
        self.assertIn("0.006897", rendered)
        self.assertIn("0.114286", rendered)
        self.assertIn("-0.084211", rendered)
        self.assertIn("0.127273", rendered)
        self.assertIn("0.145454", rendered)
        self.assertIn("-0.073684", rendered)
        self.assertIn("0.005090", rendered)
        self.assertIn("0.917241", rendered)
        self.assertIn("-0.131579", rendered)
        self.assertIn("1.000000", rendered)
        self.assertIn("0.576443", rendered)
        self.assertIn("0.477843", rendered)
        self.assertIn("0.010526", rendered)
        self.assertIn("0.171428", rendered)
        self.assertIn("0.004756", rendered)
        self.assertIn("0.005001", rendered)
        self.assertIn("0.006089", rendered)
        self.assertIn("-0.096552", rendered)
        self.assertIn("-0.078947", rendered)
        self.assertIn("0.124675", rendered)
        self.assertIn("0.140260", rendered)
        self.assertIn("77354.8", rendered)
        self.assertIn("0.007883", rendered)
        self.assertIn("0.168831", rendered)
        self.assertIn("0.006573", rendered)
        self.assertIn("0.007887", rendered)
        self.assertIn("0.004085", rendered)
        self.assertIn("0.003452", rendered)
        self.assertIn("0.184416", rendered)
        self.assertIn("0.005153", rendered)
        self.assertIn("0.138889", rendered)
        self.assertIn("0.004322", rendered)
        self.assertIn("0.006977", rendered)
        self.assertIn("0.135821", rendered)
        self.assertIn("0.004269", rendered)
        self.assertIn("0.004290", rendered)
        self.assertIn("0.003262", rendered)
        self.assertIn("0.003844", rendered)
        self.assertIn("0.004655", rendered)
        self.assertIn("0.005161", rendered)
        self.assertIn("0.007103", rendered)
        self.assertIn("0.004198", rendered)
        self.assertIn("0.004455", rendered)
        self.assertIn("0.005723", rendered)
        self.assertIn("0.005031", rendered)
        self.assertIn("0.005864", rendered)
        self.assertIn("0.005361", rendered)
        self.assertIn("0.007757", rendered)
        self.assertIn("0.006517", rendered)
        self.assertIn("0.005601", rendered)

    def test_latex_escapes_artifact_labels_and_writes_output(self) -> None:
        table_builder = load_table_builder()

        self.assertEqual(
            table_builder.latex_escape("epochs=16_hidden=8_features=1024"),
            r"epochs=16\_hidden=8\_features=1024",
        )

        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "results_tables.tex"
            table_builder.write_tables(REPO_ROOT, output_path)
            written = output_path.read_text()

        self.assertIn(r"\begin{table}", written)
        self.assertIn(r"\bottomrule", written)

    def test_committed_generated_tables_match_artifacts_and_are_input_by_paper(self) -> None:
        table_builder = load_table_builder()

        generated_path = REPO_ROOT / "paper" / "generated" / "results_tables.tex"
        main_tex = (REPO_ROOT / "paper" / "main.tex").read_text()

        self.assertEqual(generated_path.read_text(), table_builder.render_tables(REPO_ROOT))
        self.assertIn(r"\input{generated/results_tables.tex}", main_tex)


if __name__ == "__main__":
    unittest.main()
